### ISSUE TITLE
kube2pulumi improperly handles escape sequences

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/kube2pulumi#115]
### What happened?

When trying to convert objects rendered by `helm template`, `kube2pulumi` improperly handles escape sequences in quoted yaml strings. Instead of loading the yaml and treating the escapes as the thing they are escaping, it instead escapes the `\` (ie: a newline represented in the yaml as `\n` becomes `\\n` in the output code, rather than a literal newline).

Specifically, we hit this when trying to convert the cilium-agent daemonset from the cilium helm chart to python pulumi code.

### Example

The problematic yaml string is:
```yaml
                  - "/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log\n\
                    set -o errexit\nset -o pipefail\nset -o nounset\n\n# When running\
                    \ in AWS ENI mode, it's likely that 'aws-node' has\n# had a chance\
                    \ to install SNAT iptables rules. These can result\n# in dropped traffic,\
                    \ so we should attempt to remove them.\n# We do it using a 'postStart'\
                    \ hook since this may need to run\n# for nodes which might have already\
                    \ been init'ed but may still\n# have dangling rules. This is safe\
                    \ because there are no\n# dependencies on anything that is part of\
                    \ the startup script\n# itself, and can be safely run multiple times\
                    \ per node (e.g. in\n# case of a restart).\nif [[ \"$(iptables-save\
                    \ | grep -c AWS-SNAT-CHAIN)\" != \"0\" ]];\nthen\n    echo 'Deleting\
                    \ iptables rules created by the AWS CNI VPC plugin'\n    iptables-save\
                    \ | grep -v AWS-SNAT-CHAIN | iptables-restore\nfi\necho 'Done!'\n"
```

In context, the complete daemonset yaml:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: cilium-agent
    app.kubernetes.io/part-of: cilium
    k8s-app: cilium
  name: cilium
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/apply-sysctl-overwrites: unconfined
        container.apparmor.security.beta.kubernetes.io/cilium-agent: unconfined
        container.apparmor.security.beta.kubernetes.io/clean-cilium-state: unconfined
        container.apparmor.security.beta.kubernetes.io/mount-cgroup: unconfined
        prometheus.io/port: "9962"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: cilium-agent
        app.kubernetes.io/part-of: cilium
        k8s-app: cilium
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  k8s-app: cilium
              topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
        - args:
            - --config-dir=/tmp/cilium/config-map
          command:
            - cilium-agent
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CILIUM_CLUSTERMESH_CONFIG
              value: /var/lib/cilium/clustermesh/
            - name: CILIUM_CNI_CHAINING_MODE
              valueFrom:
                configMapKeyRef:
                  key: cni-chaining-mode
                  name: cilium-config
                  optional: true
            - name: CILIUM_CUSTOM_CNI_CONF
              valueFrom:
                configMapKeyRef:
                  key: custom-cni-conf
                  name: cilium-config
                  optional: true
            - name: KUBERNETES_SERVICE_HOST
              value: MZCLUSTERENDPOINT
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - "/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log\n\
                    set -o errexit\nset -o pipefail\nset -o nounset\n\n# When running\
                    \ in AWS ENI mode, it's likely that 'aws-node' has\n# had a chance\
                    \ to install SNAT iptables rules. These can result\n# in dropped traffic,\
                    \ so we should attempt to remove them.\n# We do it using a 'postStart'\
                    \ hook since this may need to run\n# for nodes which might have already\
                    \ been init'ed but may still\n# have dangling rules. This is safe\
                    \ because there are no\n# dependencies on anything that is part of\
                    \ the startup script\n# itself, and can be safely run multiple times\
                    \ per node (e.g. in\n# case of a restart).\nif [[ \"$(iptables-save\
                    \ | grep -c AWS-SNAT-CHAIN)\" != \"0\" ]];\nthen\n    echo 'Deleting\
                    \ iptables rules created by the AWS CNI VPC plugin'\n    iptables-save\
                    \ | grep -v AWS-SNAT-CHAIN | iptables-restore\nfi\necho 'Done!'\n"
            preStop:
              exec:
                command:
                  - /cni-uninstall.sh
          livenessProbe:
            failureThreshold: 10
            httpGet:
              host: 127.0.0.1
              httpHeaders:
                - name: brief
                  value: "true"
              path: /healthz
              port: 9879
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: cilium-agent
          ports:
            - containerPort: 4244
              hostPort: 4244
              name: peer-service
              protocol: TCP
            - containerPort: 9962
              hostPort: 9962
              name: prometheus
              protocol: TCP
            - containerPort: 9964
              hostPort: 9964
              name: envoy-metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              host: 127.0.0.1
              httpHeaders:
                - name: brief
                  value: "true"
              path: /healthz
              port: 9879
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          securityContext:
            capabilities:
              add:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_MODULE
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              drop:
                - ALL
            seLinuxOptions:
              level: s0
              type: spc_t
          startupProbe:
            failureThreshold: 105
            httpGet:
              host: 127.0.0.1
              httpHeaders:
                - name: brief
                  value: "true"
              path: /healthz
              port: 9879
              scheme: HTTP
            periodSeconds: 2
            successThreshold: 1
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /host/proc/sys/net
              name: host-proc-sys-net
            - mountPath: /host/proc/sys/kernel
              name: host-proc-sys-kernel
            - mountPath: /sys/fs/bpf
              mountPropagation: HostToContainer
              name: bpf-maps
            - mountPath: /var/run/cilium
              name: cilium-run
            - mountPath: /host/etc/cni/net.d
              name: etc-cni-netd
            - mountPath: /var/lib/cilium/clustermesh
              name: clustermesh-secrets
              readOnly: true
            - mountPath: /tmp/cni-configuration
              name: cni-configuration
              readOnly: true
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /var/lib/cilium/tls/hubble
              name: hubble-tls
              readOnly: true
            - mountPath: /tmp
              name: tmp
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
        - command:
            - cilium
            - build-config
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_SERVICE_HOST
              value: MZCLUSTERENDPOINT
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          name: config
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /tmp
              name: tmp
        - command:
            - sh
            - -ec
            - 'cp /usr/bin/cilium-mount /hostbin/cilium-mount;

              nsenter --cgroup=/hostproc/1/ns/cgroup --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-mount"
              $CGROUP_ROOT;

              rm /hostbin/cilium-mount

              '
          env:
            - name: CGROUP_ROOT
              value: /run/cilium/cgroupv2
            - name: BIN_PATH
              value: /opt/cni/bin
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          name: mount-cgroup
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_CHROOT
                - SYS_PTRACE
              drop:
                - ALL
            seLinuxOptions:
              level: s0
              type: spc_t
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /hostproc
              name: hostproc
            - mountPath: /hostbin
              name: cni-path
        - command:
            - sh
            - -ec
            - 'cp /usr/bin/cilium-sysctlfix /hostbin/cilium-sysctlfix;

              nsenter --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-sysctlfix";

              rm /hostbin/cilium-sysctlfix

              '
          env:
            - name: BIN_PATH
              value: /opt/cni/bin
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          name: apply-sysctl-overwrites
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_CHROOT
                - SYS_PTRACE
              drop:
                - ALL
            seLinuxOptions:
              level: s0
              type: spc_t
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /hostproc
              name: hostproc
            - mountPath: /hostbin
              name: cni-path
        - args:
            - mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpf /sys/fs/bpf
          command:
            - /bin/bash
            - -c
            - --
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          name: mount-bpf-fs
          securityContext:
            privileged: true
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
              name: bpf-maps
        - command:
            - /init-container.sh
          env:
            - name: CILIUM_ALL_STATE
              valueFrom:
                configMapKeyRef:
                  key: clean-cilium-state
                  name: cilium-config
                  optional: true
            - name: CILIUM_BPF_STATE
              valueFrom:
                configMapKeyRef:
                  key: clean-cilium-bpf-state
                  name: cilium-config
                  optional: true
            - name: KUBERNETES_SERVICE_HOST
              value: MZCLUSTERENDPOINT
            - name: KUBERNETES_SERVICE_PORT
              value: "443"
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          name: clean-cilium-state
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
                - SYS_ADMIN
                - SYS_RESOURCE
              drop:
                - ALL
            seLinuxOptions:
              level: s0
              type: spc_t
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /sys/fs/bpf
              name: bpf-maps
            - mountPath: /run/cilium/cgroupv2
              mountPropagation: HostToContainer
              name: cilium-cgroup
            - mountPath: /var/run/cilium
              name: cilium-run
        - command:
            - /install-plugin.sh
          image: quay.io/cilium/cilium:v1.13.10@sha256:aff23a5d4daf06623d10f7ff6a8a7b617c22c1f8d63f507fd33ef3a80ba4779f
          imagePullPolicy: IfNotPresent
          name: install-cni-binaries
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            seLinuxOptions:
              level: s0
              type: spc_t
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-path
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: cilium
      serviceAccountName: cilium
      terminationGracePeriodSeconds: 1
      tolerations:
        - operator: Exists
      volumes:
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
          name: cilium-run
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpf-maps
        - hostPath:
            path: /proc
            type: Directory
          name: hostproc
        - hostPath:
            path: /run/cilium/cgroupv2
            type: DirectoryOrCreate
          name: cilium-cgroup
        - hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate
          name: cni-path
        - hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
          name: etc-cni-netd
        - hostPath:
            path: /lib/modules
          name: lib-modules
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
        - name: clustermesh-secrets
          secret:
            defaultMode: 256
            optional: true
            secretName: cilium-clustermesh
        - configMap:
            name: cni-configuration
          name: cni-configuration
        - hostPath:
            path: /proc/sys/net
            type: Directory
          name: host-proc-sys-net
        - hostPath:
            path: /proc/sys/kernel
            type: Directory
          name: host-proc-sys-kernel
        - name: hubble-tls
          projected:
            defaultMode: 256
            sources:
              - secret:
                  items:
                    - key: ca.crt
                      path: client-ca.crt
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
                  name: hubble-server-certs
                  optional: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 200
    type: RollingUpdate
```

This produces the following python code:
```python
                                lifecycle=kubernetes.core.v1.LifecycleArgs(
                                    post_start=kubernetes.core.v1.LifecycleHandlerArgs(
                                        exec_=kubernetes.core.v1.ExecActionArgs(
                                            command=[
                                                "bash",
                                                "-c",
                                                "/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log\\n\\\\ set -o errexit\\nset -o pipefail\\nset -o nounset\\n\\n# When running\\\\ \\\\ in AWS ENI mode, it's likely that 'aws-node' has\\n# had a chance\\\\ \\\\ to install SNAT iptables rules. These can result\\n# in dropped traffic,\\\\ \\\\ so we should attempt to remove them.\\n# We do it using a 'postStart'\\\\ \\\\ hook since this may need to run\\n# for nodes which might have already\\\\ \\\\ been init'ed but may still\\n# have dangling rules. This is safe\\\\ \\\\ because there are no\\n# dependencies on anything that is part of\\\\ \\\\ the startup script\\n# itself, and can be safely run multiple times\\\\ \\\\ per node (e.g. in\\n# case of a restart).\\nif [[ \\\"$(iptables-save\\\\ \\\\ | grep -c AWS-SNAT-CHAIN)\\\" != \\\"0\\\" ]];\\nthen\\n    echo 'Deleting\\\\ \\\\ iptables rules created by the AWS CNI VPC plugin'\\n    iptables-save\\\\ \\\\ | grep -v AWS-SNAT-CHAIN | iptables-restore\\nfi\\necho 'Done!'\\n",
                                            ],
                                        ),
                                    ),

```

Which evaluates to:
```
/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log\n\\ set -o errexit\nset -o pipefail\nset -o nounset\n\n# When running\\ \\ in AWS ENI mode, it's likely that 'aws-node' has\n# had a chance\\ \\ to install SNAT iptables rules. These can result\n# in dropped traffic,\\ \\ so we should attempt to remove them.\n# We do it using a 'postStart'\\ \\ hook since this may need to run\n# for nodes which might have already\\ \\ been init'ed but may still\n# have dangling rules. This is safe\\ \\ because there are no\n# dependencies on anything that is part of\\ \\ the startup script\n# itself, and can be safely run multiple times\\ \\ per node (e.g. in\n# case of a restart).\nif [[ \"$(iptables-save\\ \\ | grep -c AWS-SNAT-CHAIN)\" != \"0\" ]];\nthen\n    echo 'Deleting\\ \\ iptables rules created by the AWS CNI VPC plugin'\n    iptables-save\\ \\ | grep -v AWS-SNAT-CHAIN | iptables-restore\nfi\necho 'Done!'\n
```

But it should be:
```
/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log
set -o errexit
set -o pipefail
set -o nounset

# When running in AWS ENI mode, it's likely that 'aws-node' has
# had a chance to install SNAT iptables rules. These can result
# in dropped traffic, so we should attempt to remove them.
# We do it using a 'postStart' hook since this may need to run
# for nodes which might have already been init'ed but may still
# have dangling rules. This is safe because there are no
# dependencies on anything that is part of the startup script
# itself, and can be safely run multiple times per node (e.g. in
# case of a restart).
if [[ "$(iptables-save | grep -c AWS-SNAT-CHAIN)" != "0" ]];
then
    echo 'Deleting iptables rules created by the AWS CNI VPC plugin'
    iptables-save | grep -v AWS-SNAT-CHAIN | iptables-restore
fi
echo 'Done!'
```

### Output of `pulumi about`

```
CLI          
Version      3.93.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.4.0
cloudinit   1.3.0
cockroach   0.1.0
command     0.9.1
docker      4.5.0
fivetran    0.1.12
frontegg    0.2.31
kubernetes  4.5.5
purrl       0.4.1
python      unknown
random      4.14.0
snowflake   0.37.0
tls         4.11.0

Host     
OS       fedora
Version  39
Arch     x86_64

This project is written in python: executable='/home/alex/git1/cloud/venv/bin/python3' version='3.11.7'

Current Stack: materialize/mzcloud/alexhunt

<redacted massive list of URNs>


Found no pending operations associated with materialize/alexhunt

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/alex-hunt-materialize
User           alex-hunt-materialize
Organizations  alex-hunt-materialize, materialize
Token type     personal

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: illegal semver returned by language host: kubernetes-stubs@22.6.0.post1: Invalid character(s) found in patch number "0.post1"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Thanks for the bug report @alex-hunt-materialize. We have some ongoing work to try to improve the yaml parsing here (eg. https://github.com/pulumi/kube2pulumi/pull/110) which should fix this chart.

**Comment by alex-hunt-materialize** [comment]
This is unfortunately still broken, and should be re-opened.
With v0.0.17, I get the following:
```
/cni-install.sh --enable-debug=false --cni-exclusive=true --log-file=/var/run/cilium/cilium-cni.log
\ set -o errexit
set -o pipefail
set -o nounset

# When running\ \ in AWS ENI mode, it's likely that 'aws-node' has
# had a chance\ \ to install SNAT iptables rules. These can result
# in dropped traffic,\ \ so we should attempt to remove them.
# We do it using a 'postStart'\ \ hook since this may need to run
# for nodes which might have already\ \ been init'ed but may still
# have dangling rules. This is safe\ \ because there are no
# dependencies on anything that is part of\ \ the startup script
# itself, and can be safely run multiple times\ \ per node (e.g. in
# case of a restart).
if [[ "$(iptables-save\ \ | grep -c AWS-SNAT-CHAIN)" != "0" ]];
then
    echo 'Deleting\ \ iptables rules created by the AWS CNI VPC plugin'
    iptables-save\ \ | grep -v AWS-SNAT-CHAIN | iptables-restore
fi
echo 'Done!'
```
This is much closer, but is still full of invalid escape sequences.

**Comment by aureq** [comment]
@rquitales I'm reopening this issue as @alex-hunt-materialize mentioned privately the problem, while partially fixed, is still occurring. I've shared with you the link to the internal conversation that contains a detailed example.

**Comment by rquitales** [comment]
Development for converting Kubernetes manifests to Pulumi programs has moved over to: https://github.com/pulumi/pulumi-converter-kubernetes.

This issue still affects the Kubernetes plugin converter unfortunately. A tracking bug for this in that repo is: https://github.com/pulumi/pulumi-converter-kubernetes/issues/5
